// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPaLXdPpiW4CZdD-IgbxjJFpGwAWUeKD4',
    appId: '1:510872043104:web:3c9732e89416c73db00d05',
    messagingSenderId: '510872043104',
    projectId: 'primiter-67c7b',
    authDomain: 'primiter-67c7b.firebaseapp.com',
    storageBucket: 'primiter-67c7b.firebasestorage.app',
    measurementId: 'G-QPLLPVNFBC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOfxgQhnX-074Ld4gN6h0NB9NWlKBSYjg',
    appId: '1:510872043104:android:f1ba7ca7e8728027b00d05',
    messagingSenderId: '510872043104',
    projectId: 'primiter-67c7b',
    storageBucket: 'primiter-67c7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYoI3zx2ajOmjPiWCLdN6fmw7tmcD7b9U',
    appId: '1:510872043104:ios:0605290b4c5a010ab00d05',
    messagingSenderId: '510872043104',
    projectId: 'primiter-67c7b',
    storageBucket: 'primiter-67c7b.firebasestorage.app',
    iosBundleId: 'com.primiterFlight.primiter.bookingFlight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYoI3zx2ajOmjPiWCLdN6fmw7tmcD7b9U',
    appId: '1:510872043104:ios:0605290b4c5a010ab00d05',
    messagingSenderId: '510872043104',
    projectId: 'primiter-67c7b',
    storageBucket: 'primiter-67c7b.firebasestorage.app',
    iosBundleId: 'com.primiterFlight.primiter.bookingFlight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPaLXdPpiW4CZdD-IgbxjJFpGwAWUeKD4',
    appId: '1:510872043104:web:b2ed58d6a4debbd1b00d05',
    messagingSenderId: '510872043104',
    projectId: 'primiter-67c7b',
    authDomain: 'primiter-67c7b.firebaseapp.com',
    storageBucket: 'primiter-67c7b.firebasestorage.app',
    measurementId: 'G-FQCG0VDZPB',
  );
}
